'use client';
import {useMemo} from 'react';
import {runReference} from '../lib/combat';
import type {State,Scenario,Model} from '../lib/combat';
import {replayUntil} from '../lib/replay';
export default function DeathReview({state,sc,model,onCheckpoint}:{state:State;sc:Scenario;model:Model;onCheckpoint:(t:number)=>void}){
 const reference=useMemo(()=>runReference(sc,model),[sc,model]);
 const deaths=state.logs.filter(l=>l.type==='death');
 const failure=typeof sc.failureLesson==='string'?sc.failureLesson:null;
 const inputs=state.logs.filter(l=>['cast','release','cancel','move','rejected','invalidDispel'].includes(l.type));
 return <section className="death-analysis"><p className="eyebrow">逐键复盘 · 不用一句“奶慢了”带过</p>{deaths.map((d,i)=>{const fatal=state.logs.filter(l=>l.type==='damage'&&l.target===d.target&&l.at<=d.at+.001).at(-1);const snapshot=replayUntil(sc,model,state.input,d.at,true);const target=d.target!;const waiting=snapshot.pending.filter(p=>['castComplete','bloom','embrace','replay'].includes(p.type));const actual=inputs.filter(l=>l.at>=Math.max(0,d.at-4)&&l.at<=d.at);const refHeals=reference.logs.filter(l=>l.type==='heal'&&l.target===target&&l.at<=d.at&&l.at>=Math.max(0,d.at-4)&&Number(l.effective)>0);return <article key={i} className="fatal-window"><header><span>致死窗口 {i+1}</span><h4>{d.at.toFixed(2)}秒，{state.names[target]}没撑过{fatal?.text?.split('受到')[1]?.split('，')[0]||'这一击'}</h4></header><div className="fatal-equation"><div><small>命中前生命</small><b>{Number(fatal?.before||0).toFixed(1)}</b></div><span>−</span><div><small>本次实际伤害</small><b>{Number(fatal?.amount||0).toFixed(1)}</b></div><span>→</span><div><small>治疗不能复活</small><b>阵亡</b></div></div><p className="fatal-gap">按本题这一击单独计算，至少还差 <b>{Math.max(.1,Number(fatal?.amount||0)-Number(fatal?.before||0)+.1).toFixed(1)}</b> 教学生命余量才会留下正血量；这不是下一次伤害的安全保证。</p><div className="fatal-columns"><div><h5>你的这几秒</h5>{actual.length?actual.map((l,j)=><p key={j}><time>{l.at.toFixed(2)}s</time>{l.text}</p>):<p>死亡前四秒没有施法、移动或取消记录。</p>}{waiting.map((p,j)=><p className="arrival-too-late" key={j}><time>{p.at.toFixed(2)}s</time>{p.skill}仍在等待生效{p.target!==undefined?`，施法目标是${state.names[p.target]}`:''}。它没有赶在这次致死前结算；是否能覆盖死者还取决于落点。</p>)}</div><div><h5>参考方案在这个窗口做了什么</h5>{refHeals.length?refHeals.map((l,j)=><p key={j}><time>{l.at.toFixed(2)}s</time>{l.text}</p>):<p>参考方案不是此时才抬血；可能靠更早的覆盖、减伤或位置处理避开。看下方逐键说明，不把“没治疗记录”当作没有准备。</p>}<p>这是同一初始条件下的一种存活方案，不是把你的当前局面直接替换成参考局面。</p></div></div>{failure&&<div className="fatal-lesson"><b>这道题要修正的具体判断</b><p>{failure}</p></div>}<button className="button primary" onClick={()=>onCheckpoint(Math.max(0,d.at-3))}>回到致死前{Math.min(3,d.at).toFixed(1)}秒，保留前面的操作重打 →</button></article>})}
 <details className="key-review" open={deaths.length===0}><summary>逐个按键看：成功了什么，哪里没有按出来</summary><div className="key-ledger"><div><h4>输入 / 施法侧</h4>{inputs.map((l,i)=><p className={l.type==='rejected'||l.type==='invalidDispel'?'ledger-error':''} key={i}><time>{l.at.toFixed(2)}s</time>{l.text}</p>)}{!inputs.length&&<p>本轮没有输入记录。</p>}</div><div><h4>实际生效侧</h4>{state.logs.filter(l=>['heal','coverage','bloom','arrival','dispel','death','avoided'].includes(l.type)).map((l,i)=><p key={i}><time>{l.at.toFixed(2)}s</time>{l.text}</p>)}</div></div><p>左右分开按时间读：按下技能不等于治疗到达。持续治疗按本题模型连续计算，未逐帧列在此处。</p></details></section>
}
