'use client';
import {useState} from 'react';
import {Check,EyeOff,MoveHorizontal,TriangleAlert} from 'lucide-react';
const layouts=[
 {name:'挤在一起吃花',points:[[10,17],[12,17],[12,20],[10,20]],explain:'人都在同一侧，看得见、也容易被同一片治疗碰到；但彼此站得太近。这里的问题不是“花不够大”，而是冰寒涌动会惩罚四码内叠人。',action:'先把彼此间距拉开，不为吃同一朵花重新挤回去。花覆盖不到的受伤者，用可及时到达的单体补。'},
 {name:'分散了，但隔着云雾',points:[[7,5],[28,8],[28,28],[7,31]],explain:'队友已经分开，但右侧两人与治疗者隔在云雾两边。此时反复点击治疗按钮，解决不了目标锁定问题。',action:'先确认安全侧与移动路线，让治疗者和需要治疗的人重新处于可互相治疗的位置；若有人被冰墓困住，催破墓，不能把救援职责全交给治疗。'},
 {name:'保持间距，留在可治疗一侧',points:[[7,5],[13,11],[13,25],[7,32]],explain:'把两个条件一起满足：玩家之间不挤在四码内，治疗者又没有被云雾隔在另一侧。这不是要求全队站成图里的固定形状。',action:'结界脉冲后检查真正缺血者，能等花的人用已有吐息接花；等不起的人先用来得及的单体。后续机制改变位置，再重新检查这两个条件。'}
];
const names=['坦克','元素萨满','武器战士','另一位输出'];
export default function IceFieldLesson(){const [mode,setMode]=useState(0),[pulse,setPulse]=useState(0);const healer=[6,18];const config=layouts[mode];const all=[healer,...config.points];
 return <section className="ice-lesson"><header><p className="eyebrow">本段专属空间演示 · 决意化身 / 冰区</p><h3>“能奶到”和“站得安全”，必须同时成立。</h3><p>这段有两个不同的站位约束。切换下面三种摆法，看问题到底出在距离还是云雾；不是把它们全部画成一块红地板。</p></header><div className="ice-mode" role="group" aria-label="比较冰区站位">{layouts.map((l,i)=><button key={i} aria-pressed={mode===i} onClick={()=>{setMode(i);setPulse(0)}}><span>0{i+1}</span>{l.name}</button>)}</div><div className="ice-demo"><div className="ice-board" key={`${mode}-${pulse}`}><div className="ice-cloud"><span>云雾分隔</span><small>目标锁定边界示意</small></div><div className="ice-safe-side">治疗者所在一侧</div>{config.points.map((p,i)=>{const dx=p[0]-healer[0],dy=p[1]-healer[1];const blocked=p[0]>18;const close=all.some((q,j)=>j!==i+1&&Math.hypot(q[0]-p[0],q[1]-p[1])<4);return <div key={i}><i className={`ice-heal-line ${blocked?'blocked':''}`} style={{left:healer[0]/36*100+'%',top:healer[1]/36*100+'%',width:Math.hypot(dx,dy)/36*100+'%',transform:`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`}}/><div className={`ice-person ${close?'crowded':''} ${blocked?'unreachable':''}`} style={{left:p[0]/36*100+'%',top:p[1]/36*100+'%'}}><i className={pulse?'ice-radius pulsing':'ice-radius'}/><b>{['坦','萨','战','丙'][i]}</b></div></div>})}<div className="ice-person ice-healer" style={{left:healer[0]/36*100+'%',top:healer[1]/36*100+'%'}}><b>你</b></div><div className="ice-map-caption">假设位置 · 圆环只解释四码间距<br/>不还原日志坐标，不要求照此站队</div></div><div className="ice-inspection"><h4>逐个检查，而不是只看一片绿</h4>{config.points.map((p,i)=>{const blocked=p[0]>18;const close=all.some((q,j)=>j!==i+1&&Math.hypot(q[0]-p[0],q[1]-p[1])<4);return <div key={i} className={blocked||close?'problem':'okay'}><b>{names[i]}</b><span>{blocked?<><EyeOff size={15}/>隔着云雾</>:close?<><TriangleAlert size={15}/>四码内有人</>:<><Check size={15}/>间距与同侧条件满足</>}</span></div>})}<button className="button ghost" onClick={()=>setPulse(v=>v+1)}><MoveHorizontal size={15}/>显示一次近身范围</button><p>圆是距离示意，不是本题真的在结算伤害；实战中仍以实际范围和可治疗状态为准。</p></div></div><div className="ice-explanation" aria-live="polite"><b>{config.name}</b><p>{config.explain}</p><div><span>你的处理</span><p>{config.action}</p></div></div><p className="field-boundary">本图按本节正文解释冰寒涌动与凛冽严冬的不同约束；不能由它推断11:54.1时队友确实站在这些位置，也不声称两种机制在该秒同时发生。</p></section>
}
