'use client';
import {useState} from 'react';
import {ArrowDown,Check,Layers,Target} from 'lucide-react';
const frames=[
 {title:'先把静滞准备成“能放的三口”',when:'00:26.318—00:29.925',records:['26.318 开始储存静滞','26.760 一阶段梦境吐息完成，附近有五人治疗事件','27.792 翡翠之花；29.883 青翠之拥给武器战士','29.925 静滞进入可重放状态'],decision:'静滞先进入储存状态，再记录三次治疗。准备完成，才有下一次群伤后的恢复方案。不要看到“静滞按了”就以为现在已经救了人。',counter:'这份储存是梦境吐息、翡翠之花、青翠之拥，不是别处练习里的另一套。实际存入的内容不同，释放后能给你的治疗也不同。'},
 {title:'武器战士的点伤不能等震地',when:'00:28.9附近 → 00:29.883',records:['28.9附近 武器战士同时承受箭雨与蜿蜒打击','29.883 青翠之拥给武器战士','这次单体治疗也完成了静滞的第三格'],decision:'青翠之拥此时可以交给输出，而不是永远锁在坦克身上。原因是他正承受叠加点伤；你不能为了保留一个“群疗循环”，让他一直等。飞之前仍要确认落点安全。',counter:'不能从“全队都曾中过蜿蜒打击”推出“一次蜿蜒打击打全队”。持续点伤与震地群伤是两份不同的治疗任务。'},
 {title:'震地落地后，分清治疗到达与爆发释放',when:'00:37.503—00:39.664',records:['37.503 震地命中五人','37.9附近 已记录翡翠之花治疗','38.003 已记录吞噬烈焰治疗','39.664 静滞开始重放'],decision:'先看花与转化是否真的接住缺口。若仍有人等不起后续治疗，就要升级为可及时到达的单体或已经存好的爆发，而不是看到“种花成功”就停止判断。',counter:'39.664是这场的记录，不是你必须等到的标准答案。自己的队伍若更早失去生存余量，就更早交牌。本窗口没有观察到回溯，不把它补写成玩家实际操作。'}
];
export default function QuakeLesson(){const [at,setAt]=useState(0);const f=frames[at];return <section className="quake-lesson"><p className="eyebrow">本段专属放大镜 · 塞塔里斯神庙对照场第1段</p><h3>这一次，是先救点名，再接震地。</h3><p>这里的时间只用于回查本场；箭头表示事件阅读顺序，不表示每场都要照着秒数按。</p><div className="quake-tabs">{frames.map((v,i)=><button key={i} aria-pressed={at===i} onClick={()=>setAt(i)}><span>0{i+1}</span>{['准备三格','单体插队','伤后兑现'][i]}</button>)}</div><div className="quake-frame" key={at}><header><time>{f.when}</time><h4>{f.title}</h4></header>{at===0?<div className="quake-storage">{['梦境吐息','翡翠之花','青翠之拥'].map((n,i)=><div key={n}><Layers size={22}/><small>第{i+1}格</small><b>{n}</b><Check size={16}/></div>)}</div>:at===1?<div className="quake-focus"><span>箭雨<br/>连续点伤</span><Target size={30}/><b>武器战士</b><Target size={30}/><span>蜿蜒打击<br/>另一份点伤</span></div>:<div className="quake-five">{['坦克','治疗','输出一','输出二','输出三'].map(n=><div key={n}><i/><b>{n}</b><small>该次震地受伤</small></div>)}</div>}<ol className="quake-events">{f.records.map((r,i)=><li key={i}><span>{i+1}</span><p>{r}</p>{i<f.records.length-1&&<ArrowDown size={16}/>}</li>)}</ol><div className="quake-meaning"><b>所以你的这一手是</b><p>{f.decision}</p><aside><strong>但别这样照抄</strong><p>{f.counter}</p></aside></div></div></section>}
