/* Deterministic teaching model. All values come from the explicitly labelled
   normalized lesson model, NOT live game simulation or reconstructed logs. */
import {partyNames, type PartyNames} from './party-names.ts';
export type Pos = [number,number];
export type Skill = {gcd:number;cooldown:number;essenceCost:number;range?:number;castTime?:number;channelTime?:number;directHeal?:number;stages?:{stage:number;castTime:number;directHeal:number;coverageDuration:number}[];stasisEligible?:boolean|string;echoEligible?:boolean|string;[key:string]:unknown};
export type CombatEvent = {id:string;at:number;type:string;targets:number[];name:string;amount?:number;duration?:number;interval?:number;impactAt?:number;explanation:string;damageClass?:string;hitTest?:{kind:string;center:Pos;radius:number};[key:string]:unknown};
export type Scenario = {id:string;title:string;chapterNumbers:number[];concept:string;intro:string;duration:number;difficulty:string|number;objectives:string[];initialHealth:number[];initialEssence:number;initialCoverage:number[];initialPositions:Pos[];initialFacing:number;initialCooldowns:Record<string,number>;initialBuffs:{name:string;charges:number;expiresAt:number}[];initialStasis:{state:string;slots:Slot[];expiresAt?:number};availableSkills:string[];events:CombatEvent[];briefing:string[];referenceActions:Input[];reviewRules:Rule[];acceptableAlternatives:string[];[key:string]:unknown};
export type Input = {at:number;action:string;skill?:string;target?:number;stage?:number;position?:Pos;to?:Pos;facing?:number;degrees?:number;reason?:string;[key:string]:unknown};
export type Model = {skills:Record<string,Skill>;[key:string]:unknown};
export type Slot={skill:string;target?:number;stage?:number};
export type Log={at:number;type:string;text:string;skill?:string;target?:number;amount?:number;effective?:number;eventId?:string;before?:number;after?:number;coverage?:number;consumed?:number;replay?:boolean;reason?:string;targets?:number[];[key:string]:unknown};
export type Pending = {at:number;type:string;skill?:string;target?:number;stage?:number;center?:Pos;amount?:number;event?:CombatEvent;replay?:boolean;echo?:boolean;position?:Pos};
export type Rule={id:string;concept:string;good:string;bad:string;suggestion:string;check:Record<string,unknown>;requiredForMastery?:boolean;weight?:number};
export type Dot={id:string;name:string;target:number;amount:number;next:number;end:number;interval:number;debuffType?:string;policy?:string;onDispel?:Record<string,unknown>};
export type State={t:number;names:PartyNames;health:number[];coverage:number[];reversion:number[];echo:number[];dilation:number[];zephyr:number[];positions:Pos[];facing:number;essence:number;cooldowns:Record<string,number>;proc:number;procUntil:number;gcdUntil:number;cast:null|{skill:string;start:number;end:number;target:number;stage:number};pending:Pending[];dots:Dot[];stasis:{state:string;slots:Slot[];expiresAt:number};logs:Log[];input:Input[];processed:string[];dead:number[];finished:boolean;lastMessage:string;damageHistory:{at:number;target:number;amount:number}[]};
export function createState(sc:Scenario):State{return {t:0,names:partyNames(sc.id),health:[...sc.initialHealth],coverage:[...sc.initialCoverage],reversion:[0,0,0,0,0],echo:[0,0,0,0,0],dilation:[0,0,0,0,0],zephyr:[0,0,0,0,0],positions:sc.initialPositions.map(p=>[...p] as Pos),facing:sc.initialFacing,essence:sc.initialEssence,cooldowns:{...sc.initialCooldowns},proc:sc.initialBuffs.find(b=>b.name==='生命火花')?.charges||0,procUntil:sc.initialBuffs.find(b=>b.name==='生命火花')?.expiresAt||0,gcdUntil:0,cast:null,pending:[],dots:[],stasis:{state:sc.initialStasis.state,slots:sc.initialStasis.slots.map(s=>({...s})),expiresAt:sc.initialStasis.expiresAt||0},logs:[],input:[],processed:[],dead:[],finished:false,lastMessage:'先阅读本关简报。目标、技能和站位都由你决定。',damageHistory:[]}}
const clone=(s:State):State=>structuredClone(s);
const dist=(a:Pos,b:Pos)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const alive=(s:State,i:number)=>s.health[i]>0&&!s.dead.includes(i);
function log(s:State,v:Omit<Log,'at'>){s.logs.push({at:s.t,...v} as Log)}
function heal(s:State,i:number,amount:number,skill:string,opts:Partial<Log>={}){if(!alive(s,i)){log(s,{type:'late',text:`${skill}到达时，${s.names[i]}已阵亡；治疗不能复活。`,skill,target:i,...opts});return}const before=s.health[i];s.health[i]=Math.min(100,before+amount);log(s,{type:'heal',text:`${skill} → ${s.names[i]}，实际恢复 ${(s.health[i]-before).toFixed(1)} 教学生命。`,skill,target:i,amount,effective:s.health[i]-before,before,after:s.health[i],...opts})}
function damage(s:State,i:number,amount:number,e:CombatEvent,debt=false){if(!alive(s,i))return;if(e.hitTest&&dist(s.positions[i],e.hitTest.center)>e.hitTest.radius){log(s,{type:'avoided',text:`${s.names[i]}离开危险区域，避开${e.name}。`,target:i,eventId:e.id});return}const before=s.health[i];const cov=Math.max(0,s.coverage[i]-s.t);let hit=amount;if(s.zephyr[i]>s.t&&e.damageClass==='area')hit*=.8;const deferred=!debt&&s.dilation[i]>s.t?hit*.5:0;if(deferred){hit-=deferred;for(let k=1;k<=8;k++)s.pending.push({at:s.t+k,type:'debt',target:i,amount:deferred/8,event:e})}s.health[i]=Math.max(0,before-hit);s.damageHistory.push({at:s.t,target:i,amount:Math.min(before,hit)});log(s,{type:debt?'debt':'damage',text:`${e.name} → ${s.names[i]}，承伤 ${hit.toFixed(1)}${deferred?'，另有延期伤害':''}。`,target:i,eventId:e.id,before,after:s.health[i],amount:hit,coverage:cov,deferred,areaReduced:s.zephyr[i]>s.t&&e.damageClass==='area',dilated:deferred>0,avoidable:!!e.avoidable});if(s.health[i]<=0){s.dead.push(i);log(s,{type:'death',text:`${s.names[i]}在${e.name}中阵亡。`,target:i,eventId:e.id});if(i===1){s.cast=null;s.pending=s.pending.filter(p=>p.type!=='castComplete');s.lastMessage='你已阵亡。时间轴可继续用于观察，不能再施放技能。'}}}
function coveredTargets(s:State){return s.names.map((_,i)=>i).filter(i=>{if(!alive(s,i))return false;if(i===1)return true;const d=dist(s.positions[1],s.positions[i]);const angle=Math.atan2(s.positions[i][1]-s.positions[1][1],s.positions[i][0]-s.positions[1][0])*180/Math.PI;const diff=Math.abs(((angle-s.facing+540)%360)-180);return d<=18&&diff<=60})}
function store(s:State,model:Model,skill:string,target:number,stage:number,replay:boolean){if(replay||s.stasis.state!=='recording'||!model.skills[skill]?.stasisEligible)return;s.stasis.slots.push({skill,target,stage});log(s,{type:'stored',text:`静滞第${s.stasis.slots.length}格：${skill}。`,skill,target});if(s.stasis.slots.length===3){s.stasis.state='ready';s.stasis.expiresAt=s.t+30;log(s,{type:'ready',text:'静滞储存完成，现在可以释放。'})}}
function echo(s:State,skill:string,amount:number,stage:number){const targets=s.names.map((_,i)=>i).filter(i=>alive(s,i)&&s.echo[i]>s.t);for(const i of targets){s.echo[i]=0;heal(s,i,amount*.7,`回响·${skill}`);if(skill==='梦境吐息')s.coverage[i]=s.t+[16,12,8][stage-1];if(skill==='逆转')s.reversion[i]=s.t+12}}
function resolveSkill(s:State,model:Model,p:Pending){const skill=p.skill!;const def=model.skills[skill];const target=p.target??1;const stage=p.stage||1;const rep=!!p.replay;if(!alive(s,1)&&p.type==='replay')return;
 if(skill==='梦境吐息'){const d=def.stages![stage-1];const targets=coveredTargets(s);for(const i of targets){heal(s,i,d.directHeal,skill,{replay:rep});s.coverage[i]=s.t+d.coverageDuration}log(s,{type:'coverage',text:`${rep?'重放':''}梦境吐息覆盖：${targets.map(i=>s.names[i]).join('、')}。`,skill,targets,replay:rep});if(!rep)s.cooldowns[skill]=s.t+def.cooldown;echo(s,skill,d.directHeal,stage);store(s,model,skill,target,stage,rep);return}
 if(skill==='翡翠之花'&&p.type!=='bloom'){s.pending.push({at:s.t+1.5,type:'bloom',skill,target,center:[...s.positions[target]] as Pos,replay:rep});log(s,{type:'planted',text:'翡翠之花已种下，1.5秒后才开放；现在还没有这口治疗。',skill,target,replay:rep});store(s,model,skill,target,stage,rep);return}
 if(skill==='翡翠之花'){const recipients=s.names.map((_,i)=>i).filter(i=>alive(s,i)&&dist(s.positions[i],p.center!)<=6).sort((a,b)=>s.health[a]-s.health[b]||a-b).slice(0,3);for(const i of recipients){const cov=Math.max(0,s.coverage[i]-s.t),used=Math.min(2,cov);heal(s,i,14+used*6,skill,{coverage:cov,consumed:used,replay:rep});s.coverage[i]-=used}log(s,{type:'bloom',text:`翡翠之花开放，命中${recipients.map(i=>s.names[i]).join('、')||'无人'}。`,skill,targets:recipients,replay:rep});return}
 if(skill==='青翠之拥'&&p.type!=='embrace'){s.pending.push({at:s.t+(target===1?0:.2),type:'embrace',skill,target,replay:rep});store(s,model,skill,target,stage,rep);return}
 if(skill==='青翠之拥'){if(alive(s,target)&&target!==1){s.positions[1]=[...s.positions[target]] as Pos;log(s,{type:'arrival',text:`青翠之拥到达${s.names[target]}的位置。`,target,position:s.positions[1]})}const cov=Math.max(0,s.coverage[target]-s.t),used=Math.min(4,cov);heal(s,target,32+used*6,skill,{coverage:cov,consumed:used,replay:rep});s.coverage[target]-=used;echo(s,skill,32,stage);return}
 if(skill==='活化烈焰'){heal(s,target,p.amount||24,skill,{replay:rep});echo(s,skill,p.amount||24,stage);store(s,model,skill,target,stage,rep);return}
 if(skill==='逆转'){heal(s,target,4,skill,{replay:rep});if(alive(s,target))s.reversion[target]=s.t+12;echo(s,skill,4,stage);store(s,model,skill,target,stage,rep);return}
 if(skill==='回响'){heal(s,target,4,skill);if(alive(s,target))s.echo[target]=s.t+15;return}
 if(skill==='回溯'){let total=0;for(let i=0;i<5;i++){if(!alive(s,i)||dist(s.positions[1],s.positions[i])>25)continue;const amount=s.damageHistory.filter(d=>d.target===i&&d.at>s.t-5&&d.at<=s.t).reduce((n,d)=>n+d.amount,0)*.5;heal(s,i,amount,skill);total+=amount}log(s,{type:'rewind',text:total?'按过去5秒实际承伤提供恢复，不会挡住未来伤害。':'过去5秒没有可恢复承伤，这次回溯没有兑现。',amount:total,skill});return}
 if(skill==='时间膨胀'){s.dilation[target]=s.t+8;log(s,{type:'buff',text:`${s.names[target]}获得时间膨胀；延期伤害仍需后续治疗。`,skill,target});return}
 if(skill==='微风'){for(let i=0;i<5;i++)if(alive(s,i)&&dist(s.positions[1],s.positions[i])<=20)s.zephyr[i]=s.t+8;log(s,{type:'buff',text:'微风覆盖附近队友，作用于接下来的范围伤害，不是已经掉下去的血。',skill});return}
 if(['自然平衡','灼烧之焰'].includes(skill)){const types=def.dispelTypes as string[];const removed=s.dots.filter(d=>d.target===target&&d.debuffType&&types.includes(d.debuffType)&&d.end>s.t);if(!removed.length){log(s,{type:'invalidDispel',text:`${skill}未移除效果：目标没有对应可驱散类型。`,skill,target});return}for(const d of removed){s.dots=s.dots.filter(t=>t!==d);log(s,{type:'dispel',text:`${skill}移除${s.names[target]}的${d.name}。`,skill,target,eventId:d.id,policy:d.policy});const effect=d.onDispel;if(effect&&effect.kind!=='none'){const targets=(effect.targets as number[])||[target];const e:CombatEvent={id:d.id+'-dispel',at:s.t,type:'damage',targets,name:'驱散后果',explanation:'',damageClass:'area'};if(effect.kind==='areaDamage'||effect.kind==='partyDamage')e.targets=[0,1,2,3,4];if(effect.kind==='nearbyDamage'||effect.kind==='splash'){e.targets=s.names.map((_,i)=>i).filter(i=>dist(s.positions[i],s.positions[target])<=Number(effect.radius||5)&&(!effect.excludeDebuffTarget||i!==target))}for(const i of e.targets)damage(s,i,Number(effect.amount||0),e)}}if(skill==='灼烧之焰')heal(s,target,18,skill);return}
}
function applyScript(s:State,e:CombatEvent){if(e.type==='warning'){log(s,{type:'warning',text:e.name,eventId:e.id});return}if(e.type==='move'){const positions=e.positions as Record<string,Pos>|undefined;if(positions)for(const [i,p]of Object.entries(positions))s.positions[Number(i)]=[...p];else for(const i of e.targets){const pos=(e.to||e.position) as Pos|undefined;if(pos)s.positions[i]=[...pos]}log(s,{type:'position',text:e.name,eventId:e.id});return}if(e.type==='damage'){for(const i of e.targets)damage(s,i,e.amount||0,e);return}if(e.type==='dot'||e.type==='dispel'){for(const i of e.targets)s.dots.push({id:e.id,name:e.name,target:i,amount:e.amount||0,next:e.at+(e.interval||1),end:e.at+(e.duration||0),interval:e.interval||1,debuffType:(e.debuffType||e.dispelType) as string|undefined,policy:e.dispelPolicy as string|undefined,onDispel:e.onDispel as Record<string,unknown>|undefined});log(s,{type:'debuff',text:e.name,eventId:e.id,targets:e.targets});}}
export function advance(state:State,sc:Scenario,model:Model,delta=.05):State{const s=clone(state);if(s.finished)return s;const until=Math.min(sc.duration,s.t+delta);while(s.t<until-.0001){const old=s.t;s.t=Number(Math.min(until,s.t+.05).toFixed(4));for(const e of sc.events.filter(e=>e.at<=s.t+.00001&&!s.processed.includes(e.id)).sort((a,b)=>a.at-b.at||a.id.localeCompare(b.id))){s.processed.push(e.id);applyScript(s,e)}for(const d of s.dots){while(d.next<=s.t+.00001&&d.next<=d.end+.00001){damage(s,d.target,d.amount,{id:d.id,at:s.t,type:'damage',targets:[d.target],name:d.name,explanation:'',damageClass:'dot'});d.next=Number((d.next+d.interval).toFixed(4))}}s.dots=s.dots.filter(d=>d.end>=s.t);const due=s.pending.filter(p=>p.at<=s.t+.00001).sort((a,b)=>a.at-b.at||(a.type==='debt'?-1:1));s.pending=s.pending.filter(p=>p.at>s.t+.00001);for(const p of due){if(p.type==='debt')damage(s,p.target!,p.amount!,p.event!,true);else if(p.type==='move'){s.positions[1]=p.position!;log(s,{type:'position',text:'移动到新的站位。',position:p.position})}else if(p.type==='channel'){log(s,{type:'output',text:'裂解伤害跳数；不提供治疗。',skill:'裂解',amount:6})}else {if(p.type==='castComplete')s.cast=null;resolveSkill(s,model,p)}}if(s.cast&&s.cast.end<=s.t+.00001)s.cast=null;for(let i=0;i<5;i++){if(!alive(s,i))continue;const amount=(s.coverage[i]>s.t?2.5:0)+(s.reversion[i]>s.t?2:0);if(amount)s.health[i]=Math.min(100,s.health[i]+amount*(s.t-old))}if(Math.floor((old+.00001)/5)<Math.floor((s.t+.00001)/5))s.essence=Math.min(5,s.essence+1);if(s.stasis.state==='ready'&&s.stasis.expiresAt<=s.t){s.stasis={state:'idle',slots:[],expiresAt:0};log(s,{type:'expired',text:'静滞的可重放窗口已过期。'})}}s.finished=s.t>=sc.duration;return s}
export function act(state:State,sc:Scenario,model:Model,input:Input):State{const s=clone(state);const target=input.target??1;const skill=input.skill||'';const reject=(text:string,reason:string)=>{s.lastMessage=text;log(s,{type:'rejected',text,skill,target,reason});return s};if(s.finished)return reject('本轮已结束，请复盘或重置。','finished');if(!alive(s,1))return reject('你已阵亡，不能继续施法。','dead');s.input.push({...input,at:s.t});if(input.action==='cancel'){s.cast=null;s.pending=s.pending.filter(p=>!['castComplete','channel'].includes(p.type));log(s,{type:'cancel',text:'主动停止读条或引导。'});s.lastMessage='已停止施法，接下来重新判断目标。';return s}if((input.action==='turn'||input.action==='face')){s.facing=Number(input.facing??input.degrees??input.angle??0);log(s,{type:'turn',text:`调整朝向至${s.facing}°。`});return s}if(input.action==='move'){s.cast=null;s.pending=s.pending.filter(p=>!['castComplete','channel','move'].includes(p.type));const pos=(input.position||input.to) as Pos|undefined;if(!pos)return reject('没有指定移动位置。','position');s.pending.push({at:s.t+.4,type:'move',position:[Math.max(-18,Math.min(18,pos[0])),Math.max(-18,Math.min(18,pos[1]))]});log(s,{type:'move',text:'开始移动，0.4秒后到达；站桩读条已取消。',position:pos});return s}
 if(!sc.availableSkills.includes(skill))return reject('本关没有提供这个技能。','unavailable');const def=model.skills[skill];if(!def)return reject('本模型未实现此技能。','unimplemented');if(skill==='静滞'&&s.stasis.state==='ready'){s.stasis.slots.forEach((slot,i)=>s.pending.push({at:s.t+[.1,.4,.7][i],type:'replay',...slot,replay:true}));log(s,{type:'release',text:'释放静滞，按三格顺序重放。',skill,slots:s.stasis.slots.map(t=>t.skill)});s.stasis={state:'idle',slots:[],expiresAt:0};s.lastMessage='静滞正在按储存顺序重放。';return s}if(s.pending.some(p=>p.type==='move')&&skill!=='静滞')return reject('移动尚未结束，等待到达后再施法。','moving');if(s.cast&&skill!=='静滞')return reject('正在读条／引导。需要先停止施法，不能自动插入另一招。','casting');if(def.gcd&&s.gcdUntil>s.t+.001)return reject('公共冷却尚未结束；这一键没有成功。','gcd');if((s.cooldowns[skill]||0)>s.t+.001)return reject(`${skill}还在冷却。`,'cooldown');if(s.essence<(def.essenceCost||0))return reject('精华不足；不能继续种花透支不存在的资源。','resource');const single=!['梦境吐息','静滞','回溯','微风','裂解'].includes(skill);if(single&&(!alive(s,target)||dist(s.positions[1],s.positions[target])>Number(def.range||25)))return reject('目标已阵亡或超出施法范围。','range');s.gcdUntil=Math.max(s.gcdUntil,s.t+def.gcd);s.essence-=def.essenceCost||0;if(skill!=='梦境吐息')s.cooldowns[skill]=s.t+def.cooldown;
 log(s,{type:'cast',text:`施放${skill}${single?' → '+s.names[target]:''}。`,skill,target,stage:input.stage||1,essence:s.essence,coverage:Math.max(0,s.coverage[target]-s.t)});s.lastMessage=`已施放${skill}。注意治疗真正到达的时间。`;
 if(skill==='静滞'){s.stasis={state:'recording',slots:[],expiresAt:0};return s}if(skill==='裂解'){s.cast={skill,start:s.t,end:s.t+3,target,stage:1};for(let k=1;k<=3;k++)s.pending.push({at:s.t+k,type:'channel',skill});return s}let castTime=def.castTime||0;const stage=Math.min(3,Math.max(1,input.stage||1));if(skill==='梦境吐息')castTime=def.stages![stage-1].castTime;let amount=def.directHeal;if(skill==='活化烈焰'&&s.proc>0&&s.procUntil>s.t){s.proc--;castTime=0;amount=28;log(s,{type:'proc',text:'消耗生命火花：本次活化烈焰瞬发。',skill})}if(castTime>0){s.cast={skill,start:s.t,end:s.t+castTime,target,stage};s.pending.push({at:s.t+castTime,type:'castComplete',skill,target,stage,amount});}else resolveSkill(s,model,{at:s.t,type:'direct',skill,target,stage,amount});return s}
export function runReference(sc:Scenario,model:Model,actions:Input[]=sc.referenceActions){let s=createState(sc);let n=0;const ordered=[...actions].sort((a,b)=>a.at-b.at);while(s.t<sc.duration){while(n<ordered.length&&ordered[n].at<=s.t+.001){s=act(s,sc,model,ordered[n++])}s=advance(s,sc,model,.05)}return s}
const compare=(n:number,op:string,v:number)=>op==='gt'?n>v:op==='gte'?n>=v:op==='lt'?n<v:op==='lte'?n<=v:n===v;
export function checkRule(s:State,c:Record<string,unknown>):boolean|null{const kind=String(c.kind);const target=typeof c.target==='number'?c.target:undefined;const eventId=c.eventId as string|undefined;const lo=Number(c.start??(c.window as number[]|undefined)?.[0]??0),hi=Number(c.end??(c.window as number[]|undefined)?.[1]??Infinity);const logs=s.logs.filter(l=>l.at>=lo&&l.at<hi&&(target===undefined||l.target===target)&&(!eventId||l.eventId===eventId)&&(!Array.isArray(c.eventIds)||(c.eventIds as string[]).includes(l.eventId||'')));const op=String(c.op||'gte'),v=Number(c.value??1);let n:number;
 if(kind==='all'){const checks=(c.checks||c.conditions||[]) as Record<string,unknown>[];const results=checks.map(t=>checkRule(s,t));return !checks.length?null:results.includes(false)?false:results.includes(null)?null:true}
 if(kind==='deathCount')n=s.dead.length;
 else if(kind==='targetDeaths')n=target===undefined?0:Number(s.dead.includes(target));
 else if(kind==='healthBefore')n=Number(logs.find(l=>l.type==='damage')?.before??-1);
 else if(kind==='coverageBefore'){if(Array.isArray(c.targets))n=logs.filter(l=>l.type==='damage'&&(c.targets as number[]).includes(l.target!)&&Number(l.coverage)>=Number(c.minRemaining||0)).length;else n=Number(logs.find(l=>l.type==='damage')?.coverage??-1);}
 else if(kind==='effectiveHeal')n=logs.filter(l=>l.type==='heal'&&(!c.skill||l.skill===c.skill)&&(!Array.isArray(c.skills)||(c.skills as string[]).includes(l.skill||''))).reduce((a,l)=>a+Number(l.effective||0),0);
 else if(kind==='avoidableHits')n=logs.filter(l=>l.type==='damage'&&l.avoidable).length;
 else if(kind==='invalidDispelAttempts')n=logs.filter(l=>l.type==='invalidDispel').length;
 else if(kind==='rejectedResourceActions')n=logs.filter(l=>l.type==='rejected'&&l.reason==='resource').length;
 else if(kind==='lateHealingDeaths')n=logs.filter(l=>l.type==='late').length;
 else if(kind==='emptyRewinds')n=logs.filter(l=>l.type==='rewind'&&!l.amount).length;
 else if(kind==='stasisReleaseCount')n=logs.filter(l=>l.type==='release').length;
 else if(kind==='stasisFirstSlot')return s.logs.find(l=>l.type==='stored')?.skill===(c.skill||c.value);
 else if(kind==='stasisReadyBy')return s.logs.some(l=>l.type==='ready'&&l.at<=Number(c.at??c.value??c.by??Infinity));
 else if(kind==='dispelRemoved'||kind==='safeDispel')n=logs.filter(l=>l.type==='dispel'&&(!c.skill||l.skill===c.skill)&&(!Array.isArray(c.skills)||(c.skills as string[]).includes(l.skill||''))).length;
 else if(kind==='buffAtDamage'){const l=logs.find(l=>l.type==='damage');return !!l&&(c.buff==='微风'?!!l.areaReduced:!!l.dilated)}
 else if(kind==='convertedBloomRecipients')n=new Set(logs.filter(l=>l.type==='heal'&&l.skill==='翡翠之花'&&Number(l.consumed)>0&&Number(l.effective)>=Number(c.minEffective||0)).map(l=>l.target)).size;
 else if(kind==='replayBreathTargets')n=Math.max(0,...logs.filter(l=>l.type==='coverage'&&l.replay).map(l=>l.targets?.length||0));
 else if(kind==='wastedBlooms'){const planted=s.logs.filter(l=>l.type==='bloom'&&l.at>=lo&&l.at<hi);n=planted.filter(p=>s.logs.filter(l=>l.type==='heal'&&l.skill==='翡翠之花'&&Math.abs(l.at-p.at)<.01).reduce((sum,l)=>sum+Number(l.effective),0)<1).length}
 else if(kind==='debtSettledAlive')return target!==undefined?!s.dead.includes(target)&&!s.pending.some(p=>p.type==='debt'&&p.target===target):s.dead.length===0;
 else return null;
 return compare(n,op,v)}
export function review(s:State,sc:Scenario){const out=sc.reviewRules.map(r=>({...r,passed:checkRule(s,r.check)}));const rejected=s.logs.filter(l=>l.type==='rejected');const deaths=s.logs.filter(l=>l.type==='death');const useful=s.logs.filter(l=>l.type==='heal'&&Number(l.effective)>0);return {rules:out,deaths,rejected,useful,complete:s.finished,survived:s.dead.length===0}}
